restart_file: .na
start_datetime: 2020-12-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2020-12-31 00:00:00
forecast_horizon: 0.0
sim_name: ms1_ler_flare_Simstrat
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: no
