restart_file: .na
start_datetime: 2020-09-25 00:00:00
end_datetime: .na
forecast_start_datetime: 2020-10-25 00:00:00
forecast_horizon: '0'
sim_name: GLM_2
configure_flare: configure_flare_GLM.yml
configure_obs: observation_processing.yml
use_s3: yes
