restart_file: .na
start_datetime: 2021-09-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-09-05 00:00:00
forecast_horizon: 5
sim_name: ler_gotm_noda_noda_noda
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: no
